name: Run Pre-Commit Hooks

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                    python-version: 3.x

            - name: Install dependencies
              run: pip install pre-commit

            - name: Install pre-commit hooks
              run: pre-commit install

            - name: Fetch branches
              run: |
                git fetch origin ${{ github.base_ref }}
                git fetch origin ${{ github.head_ref }}

            - name: Get list of files changed
              id: get-changed-files
              run: |
                changed_files=$(git diff --name-only origin/${{ github.base_ref }} | tr '\n' ' ')
                echo "::debug::Changed files: $changed_files"
                echo "files=$changed_files" >> $GITHUB_OUTPUT

            - name: Run pre-commit
              if: steps.get-changed-files.outputs.files != ''
              run: |
                pre-commit run --files ${{ steps.get-changed-files.outputs.files }}
